### ISSUE TITLE
Panel de control (menú de operaciones)

### ISSUE THREAD

**Issue by sgotta** [unlp-taller-tecnologias/2016-grupo-1#22]
- Barra de búsqueda.
- Mostrar listado como vista principal.

**Comment by tanoabeleyra** [comment]
## ~Solucionar superposición~ *(solucionado)*

![captura de pantalla_2016-11-22_00-13-30](https://cloud.githubusercontent.com/assets/6851095/20509596/853fd76e-b048-11e6-8410-8f3643648376.png)

**Comment by ruskofulanito** [comment]
Ver además: [https://github.com/unlp-taller-tecnologias/2016-grupo-1/issues/39](url)

Los ABM satélites podrían ser subítems de uno tipo Configuración (donde también podría ir backup)

**Comment by sgotta** [comment]
@tanoabeleyra cual era el problema de la superposición del menú? porque a mi me sigue apareciendo superpuesto.
