### ISSUE TITLE
Búsqueda de pacientes

### ISSUE THREAD

**Issue by tanoabeleyra** [unlp-taller-tecnologias/2016-grupo-1#27]
Este caso de uso describe el evento en que un usuario realiza la búsqueda de un paciente en el sistema. 
El usuario podrá ingresar uno o varios de los parámetros de búsqueda para un paciente, los parámetros son: DNI; apellido; nombre. 
En el caso del DNI el sistema hará una búsqueda absoluta, para nombre y apellido se hará una búsqueda relativa.
Todos los campos de búsqueda son opcionales, pero debe ingresarse al menos uno o el sistema retornará un mensaje de error.
Si el usuario busca por DNI como primer parámetro e ingresa uno o ambos parámetros alternativos (nombre y/o apellido), los resultados deberán responder a la búsqueda lógica [ nombre & apellido | DNI ].
Una vez que el sistema muestre los resultados de búsqueda, el usuario podrá opcionalmente realizar un filtrado seleccionando un médico en particular.
Los resultados estarán paginados.

**Comment by ruskofulanito** [comment]
La búsqueda por DNI invalida a la de nombre y apellido porque el primero es un dato único. Se puede evitar la mezcla de parámetros.

**Comment by ruskofulanito** [comment]
Para proveer la discriminación entre pacientes de servicio y prequirúrgicos se puede agregar 2 checkbox con dichas leyendas y que la búsqueda sea relativa a estos parámetros cuando están presentes. También  un checkbox que excluya a esos dos y que diga 'Nuevo' para contemplar únicamente pacientes que todavía no fueron asignados (el instante entre que se dio de alta y se registró su primera actividad).
