### ISSUE TITLE
Exportar historia clínica a PDF

### ISSUE THREAD

**Issue by tanoabeleyra** [unlp-taller-tecnologias/2016-grupo-1#29]

**Comment by ruskofulanito** [comment]
TODO: arreglar el footer para que aparezca en cada página / no funciona el approach del examen porque la historia clínica puede ocupar más de 1 pág

**Comment by ruskofulanito** [comment]
wkhtmltopdf requiere que QT esté personalizada para poder imprimir footer.
Pruebo si funciona en Windows (porque es el sistema destino) pero en caso contrario debemos decidir:
- que no haya footer, o
- elegir otra aplicación de terceros

El footer incluiría el número de página, el total de páginas, más la leyenda del servicio de cardiología y quizás la fecha y hora de generación.
@tanoabeleyra @sgotta @tomimagnelli 
PD: falta meter el logo del servicio
