### ISSUE TITLE
Exportar prequirúrgico a PDF

### ISSUE THREAD

**Issue by tanoabeleyra** [unlp-taller-tecnologias/2016-grupo-1#30]

**Comment by ruskofulanito** [comment]
La funcionalidad requiere KnpSnappyBundle que a su vez depende de la instalación de wkhtmltopdf (disponible como binario en windows y en linux). Hay que especificar el path del ejecutable en la configuración.
Por favor validen el estilo pero tengan en cuenta que los CSS deben ser incluidos dentro del código de la página (no pueden ser link rel) por lo que está bastante acotado.
Tampoco se puede utilizar fontawesome porque no se pueden cargar fuentes personalizadas.
Los checkbox y radio por ejemplo son lo que son.
La única forma de hacer esto último es imprimir URL pero la arquitectura de la aplicación no lo permite.
Arranco con visita médica.
