### ISSUE TITLE
Escala del template

### ISSUE THREAD

**Issue by ruskofulanito** [unlp-taller-tecnologias/2016-grupo-1#39]
Gente, mi monitor tiene resolución 1280x960 que es similar a uno de 17" y encuentro todos los elementos enormes y los formularios largos y con pocos datos a la vista en cada instante.
Achicando al 75% la escala en el navegador ya es bastante agradable y hasta se ve bien el panel de la izquierda y el sidebar a la derecha.
Al 67% el tamaño de los elementos a mi parecer es óptimo aunque habría que agrandar un poco el tamaño de la tipografía.
Lo propongo a debate.

**Comment by tanoabeleyra** [comment]
Si, los formularios son muy anchos, pero por ahí después de agregar bien el menú quedan mejor. Sino por ahí se podrían juntar 2 campos por fila (cuando sea conveniente).

Si están de acuerdo podríamos achicar los botones que están en la sidebar (los de ABM).

@sgotta @tomimagnelli

**Comment by sgotta** [comment]
Sí, también me parecen demasiado grandes los botones y los formularios, estoy de acuerdo.
Me parece que también quedaría bien que la barra de navegación tenga clase container-fluid en vez de container porque al haber agregado el menú lateral, la barra de navegación da un efecto de estar desplazada.
