### ISSUE TITLE
Atributos calculados

### ISSUE THREAD

**Issue by ruskofulanito** [unlp-taller-tecnologias/2016-grupo-1#40]
Existen en la especificación dos atributos calculados:
- Edad
- Médico habitual
Para el correcto registro del primero sugiero no mapear el atributo edad a la tabla, sino crear un atributo fecha_nacimiento que no se exponga en el formulario; el get/set del atributo no mapeado 'edad' calcula una fecha de nacimiento y establece el valor del campo 'fecha_nacimiento'.
Para el médico habitual también es necesario un atributo no mapeado, pero en este caso no tiene setter y el getter va a tener que realizar una consulta adicional sobre la tabla.

**Comment by tanoabeleyra** [comment]
El médico habitual se calcula bajo demanda?, porque de ser así no sería necesario un atributo, con un getter alcanzaría.

**Comment by ruskofulanito** [comment]
Es que estaba escribiendo eso mientras hablaba por teléfono, miraba los mails y discutía en la oficina.
Dije cualquier pelotudez, si justamente no tiene setter para qué un atributo.

**Comment by tanoabeleyra** [comment]
Todo bien, preguntaba por las dudas, porque no es mala la idea. Por ahí se puede recalcular el médico habitual cada vez que el paciente registra una visita y almacenarlo. Lo digo pensando en que por ahí puede haber un overhead en la búsqueda por "médico habitual" (por cada paciente tengo que recorrer todas sus visitas)..

**Comment by ruskofulanito** [comment]
Eso es cierto pero caímos en la restricción autoimpuesta de que el médico "de" un paciente es el que más veces lo atendió por una discusión que tuvimos en clase. Lo más sencillo, sin dudas, es que el médico de un paciente se determine al darlo de alta / que sea un atributo de relación con la entidad usuario y listo.
Luego, además de que no es recalculado cada vez que mostrás el listado, además no se cae en alguna posible inconsistencia (por ejemplo el médico del paciente se fue de licencia 6 meses y su médico habitual pasa a ser otro, pero no hubo la intención de reasignarlo por parte del servicio de cardiología).
Por otro lado, un paciente que tiene médico es un paciente del servicio (y cambia la forma de calcular ese discriminante, que también recurre a la tabla de visitas/exámenes).

**Comment by tanoabeleyra** [comment]
Por ahí me expresé mal, pero mi propuesta respeta lo de que "el médico de un paciente es el que más veces lo atendió".
La idea es que cada vez que un médico registra la visita médica de un paciente, recorramos todas las visitas anteriores del mismo paciente para recalcular y actualizar el médico habitual (se almacena en la BD). No se qué tan costoso será, pero obviamente menos que para N pacientes.

De esta forma evito realizar el cálculo para todos los pacientes al mismo tiempo por cada búsqueda (una locura), simplemente se lee de la BD.

**Comment by ruskofulanito** [comment]
No, se entendió. Estaba haciendo referencia al origen del problema. Estoy de acuerdo en recalcular el atributo de esa manera. Digo que hubiera sido preferible "asignar" el médico como información del paciente dándole esa responsabilidad al usuario.
