### ISSUE TITLE
Quitar propiedad required a los labels de radio buttons en examen prequirúrgico.

### ISSUE THREAD

**Issue by sgotta** [unlp-taller-tecnologias/2016-grupo-1#41]
![quitar require a los label de radio buttons en examen prequirurgico](https://cloud.githubusercontent.com/assets/2309127/20626039/a05436bc-b2f5-11e6-85d7-93c3c921f4ca.png)

**Comment by sgotta** [comment]
Intenté sacarlo pero no encuentro donde setea symfony la propiedad. La otra sería intentar sacarlo con alguna clase css pero ya sería medio parche.

**Comment by tanoabeleyra** [comment]
El grado de riesgo no era obligatorio?

**Comment by ruskofulanito** [comment]
Sí, es obligatorio. Me parece que Simón se refiere a que con el * en "Grado de riesgo" ya es suficiente y que los * en cada radio button habría que intentar sacarlos.

**Comment by sgotta** [comment]
Exacto, me sacaste las palabras de la boca jaja.

**Comment by tanoabeleyra** [comment]
Ah ah, por defecto el template de los formularios no tenía nada que diferenciara los campos obligatorios y la más fácil que se me ocurrió es hacerlo en el CSS, habría que mirar ahí.

https://github.com/unlp-taller-tecnologias/2016-grupo-1/blob/master/web/css/style.css#L150

**Comment by tanoabeleyra** [comment]
Resuelto: https://github.com/unlp-taller-tecnologias/2016-grupo-1/commit/2882cb9ed5482770db37dcf403a5039d28e87a1e
