### ISSUE TITLE
Criterios de ordenamiento

### ISSUE THREAD

**Issue by ruskofulanito** [unlp-taller-tecnologias/2016-grupo-1#48]
Agregué las cláusulas order by de las relaciones xToMany (por ejemplo, localidades en partido, motivos/diagnósticos en visita). Hay que verificar que todos los registros se muestren con un orden coherente.
Los listados de exámenes y de visitas médicas, por ejemplo, se debieran ya mostrar ordenadas porque surgen de una relación a N de paciente y está configurada.
Pero el listado de pacientes no, porque no es una relación sino la colección de entidad paciente. En estos casos se debe especificar el ordenamiento en el findalll o hacer algún overload o hardcodear algún constructor.

**Comment by tanoabeleyra** [comment]
El orden del listado de pacientes decís que sea por nombre o por apellido? (el "desempate" sería por el apellido o el nombre respectivamente)

EDIT: Ahí ví el orden en la notación (https://github.com/unlp-taller-tecnologias/2016-grupo-1/commit/cf565c652db53d5aeb302fcfd9df79aded81f380#diff-200efd5d72cd2a5ab71689d2702ca277R45), lo hago entonces por apellido.

**Comment by ruskofulanito** [comment]
Apellido asc, nombre asc, dni asc
Como para darle el orden lógico y en último lugar que desempate un dato que sería único si lo tiene.

**Comment by tanoabeleyra** [comment]
oka, te parece poner las columnas del listado en el mismo orden? Personalmente me sigue pareciendo desordenado sino (es más difícil darse cuenta del orden aplicado)..

**Comment by ruskofulanito** [comment]
Sí, totalmente, fue uno de los puntos flojos en la muestra además.
