### ISSUE TITLE
¿Quitar código postal?

### ISSUE THREAD

**Issue by tanoabeleyra** [unlp-taller-tecnologias/2016-grupo-1#57]
El código postal en este momento es una propiedad obligatoria, pero no le estamos dando ningún uso (más que informativo) y requiere que al dar de alta una localidad el administrador cuente con esa información, la busque o escriba cualquier cosa.

Si lo hacemos opcional me parece que tiene aún menos sentido, ya que es muy probable que después no se complete.

¿Hay algún motivo para no quitarlo?

**Comment by sgotta** [comment]
Contexto: el código postal estaba como obligatorio y único, pero cuando tuvimos que agregar información de los barrios (porque en el hospital reportaban pacientes por barrio), tuvimos que hacer que el código postal admita repeticiones. 

Por lo tanto, estoy de acuerdo con el Tano, no tiene sentido mantener el atributo, ya que ni siquiera sirve para identificar una localidad de forma unívoca.

**Comment by ruskofulanito** [comment]
Ni tampoco se utiliza para ningún reporte ni estadística. Coincido en que se puede eliminar.
