### ISSUE TITLE
Restricción de mínimo en DNI

### ISSUE THREAD

**Issue by ruskofulanito** [unlp-taller-tecnologias/2016-grupo-1#59]
El DNI está restringido a mínimo 10.000.000 pero existen personas con documento inferior a ese número.

**Comment by tanoabeleyra** [comment]
Mala mía, esto fue por tomarme muy literal lo de "validar que sean 8 dígitos", habría que validar por rango entonces, al menos del lado del servidor (https://github.com/unlp-taller-tecnologias/2016-grupo-1/blob/master/src/AppBundle/Entity/Paciente.php#L33).
